services:
  - type: web
    name: jarvis-web-v1-4-test
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: openrouter/free
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-3.7-flash
      - key: TAVILY_API_KEY
        sync: false
      - key: WEB_SEARCH
        value: true
      - key: PUBLIC_APP_URL
        sync: false
      - key: OPENROUTER_SITE_NAME
        value: JARVIS Web V1.4
